 ---
title: "Perreo Intenso"
author: "Arling"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(dplyr)
library(magrittr)
library(readr)
library(readxl)
library(tidyr)
library(stringr)
library(janitor)
rm(list = ls())

`%notin%` = function(x,y) !(x %in% y)
source("funciones.R")
```

```{r}
library(stopwords)
stopwords <- c(stopwords("es"), stopwords("en"))

stopwords <- c(stopwords, chartr("áéíóú", "aeiou", stopwords)) %>%
  unique()

length(stopwords)
```


```{r}
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)
```

## Lectura de datos y funciones

```{r}
proyecto_canciones <- read_excel("data/proyecto canciones.xlsx") %>%
  clean_names()

n <- proyecto_canciones$id %>%
  length()

proyecto_canciones %>%
  head()
```

## Antes de eliminar stopwords

```{r}
clean.letra <- proyecto_canciones$letra %>%
  clean_text()
```

Número de palabras únicas previo a eliminar stopwords.

```{r}
num.palabras.rep <- c()
for(i in 1:n){
  str_split(clean.letra, " ")[[i]] %>%
  unique() %>%
  length() -> num.palabras.rep[i]
}
```

## Limpieza de datos

### Limpieza de datos sin stemming, excluyendo stopwords.

```{r}
clean.letra.v1 <- lapply(clean.letra, tokenize_text, 
                         stemming = FALSE, 
                         exclude_stopwords = TRUE, nmin = 1)
```

Número de palabras únicas después de eliminar stopwords.

```{r}
num.palabras.v1 <- c()
for(i in 1:n){
  clean.letra.v1[[i]] %>% 
    unique() %>% 
    length() -> num.palabras.v1[i]
}
```

```{r}
clean.letra.df <- unlist(clean.letra.v1) %>%
  as.data.frame()

colnames(clean.letra.df) <- "word"

clean.letra.df <- clean.letra.df %>%
  group_by(word) %>%
  summarise(freq = n()) %>%
  arrange(desc(freq)) %>%
  filter(!is.na(word))
```


## 
```{r, eval=FALSE}
prueba <- procesamiento(proyecto_canciones, stemming = FALSE, 
                          exclude_stopwords = TRUE, nmin = 2)

clean.letra.df <- prueba[[1]]
clean.letra.df <- prueba[[2]]
```

```{r}
#set.seed(1234) # for reproducibility 
wordcloud(words = clean.letra.df$word, freq = clean.letra.df$freq, 
          min.freq = 1, max.words=200, random.order=FALSE, 
          rot.per=0.35,        
          colors=brewer.pal(8, "Dark2"))
```





https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a
